name: Node.js CI

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]
        mongodb-version: [4.2]

    steps:
    - name: Git checkout
      uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Start Docker for Mongodb
      run: docker run -d -p 27017:27017 mongo

    - name: Install dependencies
      run: |
        yarn --frozen-lockfile
        yarn build

    - run: yarn test
      env:
          CI: true

      
    